### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by ziyuwzf** [urbaneman/Face_crop_align_mtcnn#1]
File "Face_align_crop.py", line 78, in <module>
    crop_align_face(args)
  File "Face_align_crop.py", line 56, in crop_align_face
    ret = mtcnn.detect_face(face_img)
  File "/home/wzf/project/Face_crop_align_mtcnn-master/align_mtcnn/mtcnn_detector.py", line 410, in detect_face
    tmp = np.zeros((tmph[i], tmpw[i], 3), dtype=np.uint8)
ValueError: negative dimensions are not allowed
Exception ignored in: <bound method tqdm.__del__ of 0it [00:27, ?it/s]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/usr/local/lib/python3.5/dist-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/lib/python3.5/threading.py", line 1051, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by urbaneman** [comment]
@ziyuwzf It may be the input error. Did you slove it?

**Comment by ziyuwzf** [comment]
i changed input of images,delete some in these images,so it is solved?

**Comment by urbaneman** [comment]
I didn't meet this error and don't know what make this error. Did you crop face successful?

**Comment by ziyuwzf** [comment]
yes ,after i delete some images,i cropped face successfully

**Comment by urbaneman** [comment]
What the images you deleted look like?

**Comment by ziyuwzf** [comment]
such as multi faces in one image,or no face ,or gray image?

**Comment by urbaneman** [comment]
I have no idea, those types should be ok. What's the extension of those images? .jpg?
